import type { PetDefinition } from './types';

// Mochi the Slime: mint-green glossy blob, legless, squash-and-stretch.
// m = mint body, M = outline, h = glossy highlight, e = eye, u = mouth, . = transparent
const palette = {
  m: '#7fe3b0',
  M: '#2f8f68',
  h: '#eafff4',
  e: '#173b2c',
  u: '#1f6b4e',
};

const idle0 = [
  '................',
  '................',
  '................',
  '.....MMMM.......',
  '...MMmmmmmmMM...',
  '..MmhmmmmmmmmM..',
  '..MmhmmmmmmmmM..',
  '.MmmmmmmmmmmmmM.',
  '.MmemmmmmmemmM..',
  '.MmmmmmmmmmmmM..',
  '.MmmmmmuummmmmM.',
  '.MmmmmmmmmmmmmM.',
  '..MmmmmmmmmmM...',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
];

const idleBlink = [
  '................',
  '................',
  '................',
  '.....MMMM.......',
  '...MMmmmmmmMM...',
  '..MmhmmmmmmmmM..',
  '..MmhmmmmmmmmM..',
  '.MmmmmmmmmmmmmM.',
  '.Mm.mmmmmmm.mM..',
  '.MmmmmmmmmmmmM..',
  '.MmmmmmuummmmmM.',
  '.MmmmmmmmmmmmmM.',
  '..MmmmmmmmmmM...',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
];

const walkSquash = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '..MMMMMMMMMMMM..',
  '.MmhmmmmmmmmmmM.',
  'MmemmmmmmmmmmemM',
  'MmmmmmmuummmmmmM',
  'MmmmmmmmmmmmmmmM',
  'MMMMMMMMMMMMMMMM',
  '................',
  '................',
  '................',
  '................',
];

const walkStretch = [
  '................',
  '................',
  '.....MMMM.......',
  '....MmhmmmM.....',
  '...MmhmmmmmM....',
  '...MmmmmmmmM....',
  '..MmemmmmmemM...',
  '..MmmmmmmmmmM...',
  '..MmmmuummmmM...',
  '..MmmmmmmmmmM...',
  '...MMMMMMMM.....',
  '................',
  '................',
  '................',
  '................',
  '................',
];

const happy0 = [
  '................',
  '................',
  '.....MMMM.......',
  '...MMmmmmmmMM...',
  '..MmhmmmmmmmM...',
  '..MmmmmmmmmmM...',
  '.MmemmmmmmemmM..',
  '.MmmmmmmmmmmmmM.',
  '.MmmuuuuummmM...',
  '.MmmmmmmmmmmmM..',
  '..MmmmmmmmmmM...',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
  '................',
  '................',
];

const happy1 = [
  '................',
  '................',
  '................',
  '.....MMMM.......',
  '...MMmmmmmmMM...',
  '..MmhmmmmmmmM...',
  '.MmemmmmmmemmM..',
  '.MmmmmmmmmmmmmM.',
  '.MmmuuuuummmM...',
  '.MmmmmmmmmmmmM..',
  '..MmmmmmmmmmM...',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
  '................',
  '................',
];

const eat0 = [
  '................',
  '................',
  '................',
  '................',
  '.....MMMM.......',
  '...MMmmmmmmMM...',
  '..MmhmmmmmmmM...',
  '.MmemmmmmmemmM..',
  '.MmmmmmmmmmmmmM.',
  '.MmmuuuuummmM...',
  '.MmmmmmmmmmmmM..',
  '..MmmmmmmmmmM...',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
  '................',
];

const eat1 = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '....MMMMMMMM....',
  '..MMmmmmmmmmMM..',
  '.MmhmmmmmmmmmmM.',
  '.MmemmmmmmemmmM.',
  '.MmmuuuuummmmM..',
  '.MmmmmmmmmmmmmM.',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
  '................',
  '................',
];

const sleep0 = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '..MMMMMMMMMMMM..',
  '.MmhmmmmmmmmmmM.',
  '.Mm.mmmmmmmm.mM.',
  '.MmmmmmmmmmmmmM.',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
];

const sleep1 = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '..MMMMMMMMMMMM..',
  '.Mmh.mmmmmm.hmM.',
  '.MmmmmmmmmmmmmM.',
  '..MMMMMMMMMMMM..',
  '................',
  '................',
];

const mochi: PetDefinition = {
  id: 'mochi',
  name: 'Mochi',
  species: 'Slime',
  blurb: 'Squishy mint blob. Maximum bounce.',
  grid: { width: 16, height: 16 },
  palette,
  animations: {
    idle: { frames: [idle0, idleBlink], fps: 2 },
    walk: { frames: [walkSquash, walkStretch], fps: 4 },
    happy: { frames: [happy0, happy1], fps: 5 },
    eat: { frames: [eat0, eat1], fps: 3 },
    sleep: { frames: [sleep0, sleep1], fps: 1 },
  },
};

export default mochi;
