import type { PetDefinition } from './types';

// Nova the Dragon: purple, tiny wings, tail, little horns.
// p = purple body, P = deep-purple outline, w = wing lavender, b = belly,
// h = horn, e = eye, s = sparkle
const palette = {
  p: '#9b6bf0',
  P: '#4b2a86',
  w: '#c9b2ff',
  b: '#e4d6ff',
  h: '#ffd97a',
  e: '#221040',
  s: '#fff3c4',
};

const idle0 = [
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PppppppppppppP.',
  '.PpeppppppepppP.',
  '.PppppppppppppP.',
  'wPppbbbbbbbbppPw',
  'w.PpbbbbbbbbpP.w',
  'w.PppppbbppppP.w',
  '.wPpppppppppPw..',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '...PP......PP...',
  '................',
  '................',
];

const idleBlink = [
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PppppppppppppP.',
  '.Pp.pppppp.ppPP.',
  '.PppppppppppppP.',
  'wPppbbbbbbbbppPw',
  'w.PpbbbbbbbbpP.w',
  'w.PppppbbppppP.w',
  '.wPpppppppppPw..',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '...PP......PP...',
  '................',
  '................',
];

const walk0 = [
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PppppppppppppP.',
  '.PpeppppppepppP.',
  'wPppppppppppppP.',
  'w.PpbbbbbbbbpPw.',
  'w.PpbbbbbbbbpP.w',
  '.wPpppppppppPw..',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '...PP.....PP....',
  '..PP.......PP...',
  '................',
  '................',
];

const walk1 = [
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PppppppppppppP.',
  '.PpeppppppepppP.',
  '.PppppppppppppPw',
  '.wPpbbbbbbbbpP.w',
  'w.PpbbbbbbbbpP.w',
  'w.PppppppppppPw.',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '....PP.....PP...',
  '...PP.......PP..',
  '................',
  '................',
];

const happy0 = [
  's............s..',
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PpeppppppepppP.',
  'wPppppppppppppPw',
  'w.PpbbbbbbbbpP.w',
  'w.PpbbbbbbbbpP.w',
  '.wPppppbbppppPw.',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '...PP......PP...',
  '................',
  '................',
  '................',
];

const happy1 = [
  '................',
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PpeppppppepppP.',
  'wPppppppppppppPw',
  'w.PpbbbbbbbbpP.w',
  'w.PpbbbbbbbbpP.w',
  '.wPppppbbppppPw.',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '...PP......PP...',
  '..PP........PP..',
  '................',
  '................',
];

const eat0 = [
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PppppppppppppP.',
  '.PpeppppppepppP.',
  '.PppppppppppppP.',
  '.wPpbbbbbbbbpPw.',
  '..PpbbbbbbbbpP..',
  '..PppppbbppppP..',
  '..PppppppppppP..',
  '..PPPPPPPPPPPP..',
  '...PP......PP...',
  '................',
  '................',
  '................',
];

const eat1 = [
  '................',
  '..h..........h..',
  '..Ph........hP..',
  '..PppP....PppP..',
  '.PpppPPPPPPpppP.',
  '.PppppppppppppP.',
  '.PpeppppppepppP.',
  '.PppppppppppppP.',
  '.wPpbbbbbbbbpPw.',
  '..PpbbbbbbbbpP..',
  '..PppppbbppppP..',
  '..PPPPPPPPPPPP..',
  '...PP......PP...',
  '................',
  '................',
  '................',
];

const sleep0 = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '.PpppPPPPPPpppP.',
  'wPp.pppppp.pp.Pw',
  'w.PpbbbbbbbbpP.w',
  '.wPppppppppppPw.',
  '..PPPPPPPPPPPP..',
  '................',
  '................',
];

const sleep1 = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '.PpppPPPPPPpppP.',
  'wPp.pppppp.pp.Pw',
  'w.PpbbbbbbbbpP.w',
  '.wPPPPPPPPPPPPw.',
  '................',
  '................',
];

const nova: PetDefinition = {
  id: 'nova',
  name: 'Nova',
  species: 'Dragon',
  blurb: 'Smol purple dragon. Big dreams.',
  grid: { width: 16, height: 16 },
  palette,
  animations: {
    idle: { frames: [idle0, idleBlink], fps: 2 },
    walk: { frames: [walk0, walk1], fps: 6 },
    happy: { frames: [happy0, happy1], fps: 6 },
    eat: { frames: [eat0, eat1], fps: 4 },
    sleep: { frames: [sleep0, sleep1], fps: 1 },
  },
};

export default nova;
